# Project
mod_version=1.6.1
group=org.cyclops.integratednbt
java_version=25

# Common
minecraft_version=26.2
mod_name=IntegratedNBT
mod_author=Rin Tepis, rubensworks (aka kroeser)
mod_id=integratednbt
license=MIT
github_url=https://github.com/CyclopsMC/IntegratedNBT
issue_tracker_url=https://github.com/CyclopsMC/IntegratedNBT/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/integrated-nbt
description=Integrated NBT is an addon for Integrated Dynamics. It offers a simpler way of extracting deeply nested NBT values.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

curseforge_project_id=380998
modrinth_project_id=2PVU5Uck

# NeoForge
neoforge_version=26.2.0.6-beta
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/integrated-nbt.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true

# Dependencies
cyclopscore_version=1.30.0-1038
integrateddynamics_version=1.33.4-1858
commoncapabilities_version=2.11.8-360
